In [39]:
import numpy as np

def identify_function(x):
    return x

def step_function(x):
    return np.array(x > 0, dtype=np.int)

def sigmoid(x):
    return 1 / ( 1 + np.exp(-x))

def sigmoid_grad(x):
    return (1.0 - sigmoid(x)) * sigmoid(x)

def relu(x):
    return np.maximum(0, x)

def relu_grad(x):
    grad = np.zeros(x.shape)
    grad[x>=0] = 1
    return grad

def softmax(x):
    if x.ndim == 2:
#         x = x.T
#         x = x - np.max(x, axis=0)
        z = np.max(x, axis=0)
        print(z)
        y = np.exp(x) / np.sum(np.exp(x), axis=0)
        return y.T
    
    x = x - np.max(x)
    return (np.exp(x))/np.sum(np.exp(x))

scores2D = np.array([[1, 2, 3, 6],
                     [2, 4, 5, 6],
                     [3, 8, 7, 6]])
softmax(scores2D)



[3 8 7 6]


array([[0.09003057, 0.24472847, 0.66524096],
       [0.00242826, 0.01794253, 0.97962921],
       [0.01587624, 0.11731043, 0.86681333],
       [0.33333333, 0.33333333, 0.33333333]])

In [49]:
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])
a = a.reshape([4,2,4])
print(a)
a[1][0][0]

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]


8