In [33]:
import numpy as np
np.arange(2)
np.arange(2).reshape(-1,1)*np.arange(2)

array([[0, 0],
       [0, 1]])

In [9]:
import numpy as np

a = np.arange(24).reshape(6,4)

data = np.loadtxt('./3minTensorflow/data.csv', delimiter=',', unpack=True, dtype='float32')
print(data)
print(np.random.uniform(0,1,100))

[[0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1.]]
[0.8423507  0.84233945 0.96456146 0.14748058 0.88467063 0.24915804
 0.79058382 0.93922479 0.48132672 0.26868105 0.58621684 0.83762675
 0.81089038 0.28001071 0.31295792 0.09385369 0.65697946 0.70919205
 0.04609873 0.27646695 0.01782589 0.61219296 0.42493868 0.85372214
 0.30197379 0.62619396 0.69040179 0.36351688 0.48071632 0.39523395
 0.47672828 0.68133336 0.77836772 0.02476199 0.50488068 0.08671405
 0.9100567  0.84684902 0.5155029  0.43638221 0.4701256  0.00529725
 0.93341491 0.81222775 0.15480105 0.81019101 0.73113848 0.61439044
 0.81167908 0.93881805 0.24084454 0.32876245 0.86262762 0.50168171
 0.86800966 0.48186689 0.13182688 0.51414259 0.36656186 0.97580981
 0.89762871 0.52802992 0.32309144 0.53836766 0.61593532 0.99995164
 0.52296675 0.34235069 0.93926386 0.77533251 0.25899537 0.10258559
 0.42526728 0.54726096 0.71689029 0.47921777 0.93381259 0.185034
 0.56477216 0.31328553 0.

In [18]:
 np.arange(15).reshape(3,1,5)

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [20]:
np.arange(45).reshape(3,3,5) +  np.arange(15).reshape(3,1,5)

array([[[ 0,  2,  4,  6,  8],
        [ 5,  7,  9, 11, 13],
        [10, 12, 14, 16, 18]],

       [[20, 22, 24, 26, 28],
        [25, 27, 29, 31, 33],
        [30, 32, 34, 36, 38]],

       [[40, 42, 44, 46, 48],
        [45, 47, 49, 51, 53],
        [50, 52, 54, 56, 58]]])

In [74]:
a = np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [56]:
b=np.arange(4)

In [80]:
b= a[:,:,:,np.newaxis]
b

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]],


       [[[12],
         [13],
         [14],
         [15]],

        [[16],
         [17],
         [18],
         [19]],

        [[20],
         [21],
         [22],
         [23]]]])

In [81]:
np.arange(2).reshape(-1,1) * np.arange(2)

array([[0, 0],
       [0, 1]])

In [62]:
import numpy as np
a = np.arange(12).reshape(2,3,2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [65]:
a[:,np.array([0,1,1,0,1,1,1,1]).reshape(4,2), np.array([0,1,1,0,1,1,1,1]).reshape(4,2)]


array([[[0, 3],
        [3, 0],
        [3, 3],
        [3, 3]],

       [[6, 9],
        [9, 6],
        [9, 9],
        [9, 9]]])

In [42]:
a[:,:,:,np.array([0,1,1,0]).reshape(2,2)]

array([[[[[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7]],

          [[ 4,  5,  6,  7],
           [ 0,  1,  2,  3]]],


         [[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7]],

          [[ 4,  5,  6,  7],
           [ 0,  1,  2,  3]]],


         [[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7]],

          [[ 4,  5,  6,  7],
           [ 0,  1,  2,  3]]]],



        [[[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7]],

          [[ 4,  5,  6,  7],
           [ 0,  1,  2,  3]]],


         [[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7]],

          [[ 4,  5,  6,  7],
           [ 0,  1,  2,  3]]],


         [[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7]],

          [[ 4,  5,  6,  7],
           [ 0,  1,  2,  3]]]]],




       [[[[[16, 17, 18, 19],
           [20, 21, 22, 23]],

          [[20, 21, 22, 23],
           [16, 17, 18, 19]]],


         [[[16, 17, 18, 19],
           [20, 21, 22, 23]],

          [[20, 21, 22, 23],
           [16, 17, 18, 19]]],


         [[[16, 17

In [20]:
np.ones(4)[0:1]

array([1.])

In [29]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])